### ISSUE TITLE
access HLT information for an event.

### ISSUE THREAD

**Issue by vardanaloyan** [cms-nanoAOD/nanoAOD-tools#168]
Hello dear colleagues !
I want to do preselection in MC dataset, requiring events to pass HLT trigger.
I am using this instructions -> https://github.com/cms-nanoAOD/nanoAOD-tools

I modify the script https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/examples/exampleAnalysis.py 

And add the HLT collection like in the example (Electron, Moun, Jet)

After executing, the code crushes giving this error message:

    if not branch: raise RuntimeError, "Unknown branch %s" % branchName
RuntimeError: Unknown branch nHLT

As error said there is no nHLT branch.

Any suggestions to this error ?

And how to correctly access HLT informations in NANOAOD datasets...
Thanks in advance!

trigger - > HLT_QuadPFJet105_88_76_15_BTagCSV_p013_VBF2
dataset - > /VBFHToBB_M-125_13TeV_powheg_pythia8_weightfix/RunIIFall17NanoAODv4-PU2017_12Apr2018_Nano14Dec2018_102X_mc2017_realistic_v6-v1/NANOAODSIM

**Comment by sroychow** [comment]
I checked with one of the files from this dataset and the information for this trigger path is present.  The trigger bits are saved in the trees as described [here](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Trigger). 
In the example analysis if you do the following, it should work.
preselection="HLT_QuadPFJet105_88_76_15_BTagCSV_p013_VBF2"
p=PostProcessor(".",files,cut=preselection,branchsel=None,modules=[ExampleAnalysis()],noOut=True,histFileName="histOut.root",histDirName="plots")

**Comment by NJManganelli** [comment]
When you need to access the information inside of the PostProcessor, any of the following code may be added inside the analyze function:

trig = "HLT_QuadPFJet105_88_76_15_BTagCSV_p013_VBF2"
if hasattr(event, trig):
    if getattr(event, trig):
        doSomethingWhenTriggerFired()
    else:
        doSomethingWhenNotFired()

#Another way to access the value, using a trigger that you're absolutely certain is present:
triggerValue = event.HLTs_QuadPFJet105_88_76_15_BTagCSV_p013_VBF2

Additionally, you can use the Object method to gather all branches that share a common prefix (underscore delimited), such as below. Note that the "HLT_" has been stripped from the trigger list here, just as when you access a variable from a Collection (of Objects) as in some of the examples (i.e., you would use j.pt or getattr(j, "pt") to get the transverse momentum, even though this is nominally stored in an array-type branch called Jet_pt).

triggers = ["QuadPFJet105_88_76_15_BTagCSV_p013_VBF2", "SomeOtherTrigger"]
HLTs = Object(event, "HLT")
for trig in triggers:
    if hasattr(HLTs, trig) and getattr(HLTs, trig):
        doSomething

#Another way to access the value, using a trigger that you're absolutely certain is present.
#Since the value no longer has the "HLT_" in the name when the triggers are grouped using Object()...
triggerValue = HLTs.QuadPFJet105_88_76_15_BTagCSV_p013_VBF2

**Comment by NJManganelli** [comment]
Just reading the original post again, what probably happened here (without seeing the code itself) is that you tried calling Collection(event, "HLT"). The issue there was that Collection assumes there must be a branch with the name "nHLT" in that case, to dictate the length of the array. HLT branches, however, are scalar. For each trigger, there is a separate branch, with only one value. Using Object instead of Collection will solve that issue, and there won't be anything to iterate through, since it's not structured like the jet, lepton collections.

**Comment by vardanaloyan** [comment]
Thanks for your replies. Currently i do the preselection by the way
`
def analyze(self, event):
    hltTrig = "HLT_QuadPFJet105_88_76_15_BTagCSV_p013_VBF2"
    return getattr(event, hltTrig, False)
`
