### ISSUE TITLE
Add btagSF module

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/nanoAOD-tools#17]

**Comment by veelken** [comment]
How about we port the BTagWeightCalculator from Heppy (
 https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/PhysicsTools/Heppy/python/physicsutils/BTagWeightCalculator.py ) to the new Module interface ( defined in https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/framework/eventloop.py ). Would't this be sufficient ?

I volunteer to do this, if you agree it's the way to go :)

**Comment by arizzi** [comment]
I'd like to speed it up

Il 18 ott 2017 2:59 PM, "Christian Veelken" <notifications@github.com> ha
scritto:

**Comment by veelken** [comment]
Hi Andrea,

ok, I will wait for your implementation then :)

**Comment by arizzi** [comment]
@veelken I'm not sure I'll have time to make a faster version soon, anyhow there are several heppy btag weighters... I think the one we used in the end for VHbb was
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/btagSF.py
so if you want you can import that one as a first version (an then we can speed it up later)

@peruzzim  also pointed to the CMG equivalent of the btagSF.py, i.e. : https://github.com/peruzzim/cmgtools-lite/blob/80X_M17_postMoriond/TTHAnalysis/python/tools/BTagCSVFullShape.py

**Comment by veelken** [comment]
@peruzzim Marco, do you have a preference which b-tag SV method to use ? I have been using the code in the VHbbAnalysis repository from Andrea for the ttH with H->tautau analysis with the 2016 data and would be happy to keep using it. The FullShape correction is, however, the more general method. Or shall we provide both methods in the nanoAOD-tools and let the nanoAOD user decide which one to use ? I would obviously like to make sure that the code that I convert (whichever of the two it is) actually gets used :)

**Comment by arizzi** [comment]
@peruzzim said that the CMG version is a port to CMG of the btagSF.py from vhbb so you can start from btagSF.py

**Comment by peruzzim** [comment]
@veelken, I think that both the cut-based scale factors and the full shape reweighting are needed.

@arizzi, actually the two scripts look quite different, because the CMG one uses more recent CMSSW integrated code (libCondFormatsBTauObjects and libCondToolsBTau) instead of the earlier standalone version, but it's there for full shape reweighting only (see the comment in the file).

The CMG older version based on the standalone is this one, I think this is more similar to vhbb, but I don't know if it's really equivalent:
https://github.com/peruzzim/cmgtools-lite/blob/80X_M17_postMoriond/TTHAnalysis/python/tools/BTagScaleFactors.py

I think the best would be to use the calibrators integrated in CMSSW also for the cut-based, and avoid the local compilation of the shared library. This is not there already, needs to be written.

**Comment by veelken** [comment]
Hi Marco, 
thank you for the confirmation. I will start to port the code in https://github.com/peruzzim/cmgtools-lite/blob/80X_M17_postMoriond/TTHAnalysis/python/tools/BTagScaleFactors.py and implement the update to processing the systematic uncertainties by std::vector<std::string>.

**Comment by veelken** [comment]
Hi, I have implemented a Module that computes the "regular" and the "shape correction" b-tag scale factors. The corresponding PR is https://github.com/cms-nanoAOD/nanoAOD-tools/pull/22

**Comment by arizzi** [comment]
@peruzzim on my side it is fine to use the CMSSW version but this imply another "cmssw dependency" so a failure to run standalone (same as for JECs) ... so we may want to add in the standalone compile script something to fetch and local compile JEC and Btag calib interfaces

**Comment by arizzi** [comment]
#22 merged
