### ISSUE TITLE
lepton jetPtRatio and jetBtagCSV variables for ttH analysis

### ISSUE THREAD

**Issue by veelken** [cms-nanoAOD/nanoAOD-tools#19]
Hi,

in the ttH analysis we use the lepton/jet pT ratio and the CSV discriminator associated to the lepton by dR, which we computed in Heppy so far ( using https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/PhysicsTools/Heppy/python/analyzers/objects/JetAnalyzer.py and https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/python/vhbbobj.py#L54-L55 ).

I am wondering if these variables are of general interest ?

I would volunteer to implement them in a Module in https://github.com/cms-nanoAOD/nanoAOD-tools/tree/master/python/postprocessing/examples in case you think these variables are of general interest.

**Comment by arizzi** [comment]
@veelken you can compute them already in Draw as:
Muon_pt/Jet_pt[Muon_idxJet]
and 
Jet_btagWhatever[Muon_idxJet]

**Comment by peruzzim** [comment]
@arizzi for the btag yes, not for the ptratio because the jet calibration used in that case is not the standard one. I don't think it's really needed to have it in the final ntuple though, it can be added easily for specific use cases as it's available in production (transient now) to evaluate the lepton MVA.

**Comment by arizzi** [comment]
the leptonMVA has been consolidated in the Muon objects, you do not need to compute it yourself

**Comment by arizzi** [comment]
can we close this?

**Comment by veelken** [comment]
Yes, please go ahead and close this thread.
