### ISSUE TITLE
Smearing is wrong for jets without matched Gen

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/nanoAOD-tools#72]
https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetSmearer.py#L111-L113

should be gaussian, not flat and should use the computed sigma!

@rappoccio @veelken

**Comment by veelken** [comment]
Hi,

if I understand correctly, lines 111-113 of https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetSmearer.py need to be replaced by
    self.rnd.Gaus(1., sigma)
and line 184 needs to be replaced by
    self.rnd.Gaus(1., sigma)
I agree to change the code in both cases. 

My experience with jets that are not generator-level matched is that these jets are either entirely due to pileup or are due to low pT jets from the hard-scatter interaction, which pick up a lot of pileup in addition.

**Comment by rappoccio** [comment]
Yes, I concur, that is also my experience.

**Comment by veelken** [comment]
Here is the corresponding pull request: https://github.com/cms-nanoAOD/nanoAOD-tools/pull/73
